// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoopBuddy.Data.Database.Context;

namespace PoopBuddy.Data.Database.Migrations
{
    [DbContext(typeof(PoopingContext))]
    [Migration("20190514171413_SubscribersInitialMigration")]
    partial class SubscribersInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PoopBuddy.Data.Database.Entities.PoopingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<TimeSpan>("Duration");

                    b.Property<Guid>("ExternalId");

                    b.Property<decimal>("WagePerHour");

                    b.HasKey("Id");

                    b.ToTable("Poopings");
                });

            modelBuilder.Entity("PoopBuddy.Data.Database.Entities.SubscriberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Auth");

                    b.Property<string>("Endpoint");

                    b.Property<DateTime?>("ExpirationTime");

                    b.Property<Guid>("ExternalId");

                    b.Property<string>("P256Dh");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
