// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PoopBuddy.Data.Database.Context;

namespace PoopBuddy.Data.Database.Migrations
{
    [DbContext(typeof(PoopingContext))]
    partial class PoopingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PoopBuddy.Data.Entities.PoopingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<TimeSpan>("Duration");

                    b.Property<Guid>("ExternalId");

                    b.Property<decimal>("WagePerHour");

                    b.HasKey("Id");

                    b.ToTable("Poopings");
                });
#pragma warning restore 612, 618
        }
    }
}
